# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

# RGB Underglow/under key RGBW leds
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP_SPI=y
CONFIG_SPI=y
CONFIG_ZMK_EXT_POWER=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y

# helps to pair and connect for certain wireless chipset firmware versions
CONFIG_BT_CTLR_PHY_2M=n
